### ISSUE TITLE
Some questions about the difference of your model and your provided code:

### ISSUE THREAD

**Issue by jingyishicn** [zengqunzhao/MA-Net#11]
Hello Mr.Zhao, thanks for your work in facial expression recognition. When I try to read your paper and understand the code that you provided, I met with this issues:
 in Fig.2, the feature map was divided by channel into four groups. However, the left stage's  first block(called block 1) enter one 3 x 3 conv, and then it is concatenated with block2. And in the right stage, the block 1 was concatenated in the last. in other words, it is not absolutely symmetry. However, in your code, we find that the block 1 was the first added in both stage, which means it isn't the same as the paper told. Can you explain it clearer?

**Comment by zengqunzhao** [comment]
> Hello Mr.Zhao, thanks for your work in facial expression recognition. When I try to read your paper and understand the code that you provided, I met with this issues: in Fig.2, the feature map was divided by channel into four groups. However, the left stage's first block(called block 1) enter one 3 x 3 conv, and then it is concatenated with block2. And in the right stage, the block 1 was concatenated in the last. in other words, it is not absolutely symmetry. However, in your code, we find that the block 1 was the first added in both stage, which means it isn't the same as the paper told. Can you explain it clearer?

> Hello Mr.Zhao, thanks for your work in facial expression recognition. When I try to read your paper and understand the code that you provided, I met with this issues: in Fig.2, the feature map was divided by channel into four groups. However, the left stage's first block(called block 1) enter one 3 x 3 conv, and then it is concatenated with block2. And in the right stage, the block 1 was concatenated in the last. in other words, it is not absolutely symmetry. However, in your code, we find that the block 1 was the first added in both stage, which means it isn't the same as the paper told. Can you explain it clearer?

Hi, thanks for your attention and feedback.
Sorry for the wrong version of the code, we have updated the code.

Best,
Zengqun
