### ISSUE TITLE
数据集的问题

### ISSUE THREAD

**Issue by xiaoliaobin** [zengqunzhao/MA-Net#3]
你好，请问能提供一份你使用的AffectNet、Sfew数据集和FED-RO数据集吗？非常感谢！！

**Comment by zengqunzhao** [comment]
> 你好，请问能提供一份你使用的AffectNet、Sfew数据集和FED-RO数据集吗？非常感谢！！
你好，感谢你对我们工作的关注。
关于AffectNet数据集，你可以从http://mohammadmahoor.com/affectnet/申请下载；
关于SFEW数据集，你可以从http://mohammadmahoor.com/affectnet/申请下载；
关于FED-RO，你只可以直接从https://github.com/mysee1989/PG-CNN下载，README.md中有下载链接。

祝好，
增群

**Comment by zengqunzhao** [comment]
> 你好，请问能提供一份你使用的AffectNet、Sfew数据集和FED-RO数据集吗？非常感谢！！


你好，感谢你对我们工作的关注。

关于AffectNet数据集，你可以从http://mohammadmahoor.com/affectnet/申请下载；
关于SFEW数据集，你可以从http://mohammadmahoor.com/affectnet/申请下载；
关于FED-RO，你只可以直接从https://github.com/mysee1989/PG-CNN下载，README.md中有下载链接。

祝好，
增群

**Comment by xiaoliaobin** [comment]
感谢你的回复，我想请问一下，我在复现你的论文的时候，在RAF-DB上能达到88%以上，但是在SFEW和AffectNet数据集上训练的效果都不是很好，请问你代码在训练AffectNet数据集时有什么改动吗？

**Comment by zengqunzhao** [comment]
> 感谢你的回复，我想请问一下，我在复现你的论文的时候，在RAF-DB上能达到88%以上，但是在SFEW和AffectNet数据集上训练的效果都不是很好，请问你代码在训练AffectNet数据集时有什么改动吗？

首先需要在MS-Celeb上预训练网络，这步你应该做了。对于SFEW数据集，和之前大部分的工作一样，我们在FER2013数据集上预训练的网络，然后在SFEW上微调下。 另外SFEW数据量太小，完全就是过拟合的，所以每次结果波动挺大的，对于batch size和learning rate也挺敏感的，因此要根据你的数据和环境调整下。对于AffectNet数据集，因为他的训练集是unbalanced，而测试是balanced，因此和之前的方法一样，我们使用了Imbalanced Dataset Sampler，这个代码可以在https://github.com/ufoym/imbalanced-dataset-sampler找的。
以上问题在论文中都有说明。

**Comment by xiaoliaobin** [comment]
非常感谢你的回复！

**Comment by xiaoliaobin** [comment]
你好，我申请不到SFEW数据集，请问你能发我一份吗？非常感谢！
