### ISSUE TITLE
model = torch.load('./checkpoint/Pretrained_on_MSCeleb.pth.tar')   error

### ISSUE THREAD

**Issue by omtrix** [zengqunzhao/MA-Net#5]
when I run the code :checkpoint = torch.load('./checkpoint/Pretrained_on_MSCeleb.pth.tar')
then I got:
Traceback (most recent call last):
  File "/home/hyj/桌面/master_projects/MA-Net-main/just_test.py", line 5, in <module>
    model = torch.load('./checkpoint/Pretrained_on_MSCeleb.pth.tar')
  File "/home/hyj/anaconda3/envs/hyj_env/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/hyj/anaconda3/envs/hyj_env/lib/python3.8/site-packages/torch/serialization.py", line 787, in _legacy_load
    result = unpickler.load()
AttributeError: Can't get attribute 'RecorderMeter' on <module '__main__' from '/home/hyj/桌面/master_projects/MA-Net-main/just_test.py'>

**Comment by zengqunzhao** [comment]
> 

Thanks for your interest.
You can try by adding "import main import RecorderMeter" in your just_test.py.

**Comment by zengqunzhao** [comment]
> when I run the code :checkpoint = torch.load('./checkpoint/Pretrained_on_MSCeleb.pth.tar') then I got: Traceback (most recent call last): File "/home/hyj/桌面/master_projects/MA-Net-main/just_test.py", line 5, in model = torch.load('./checkpoint/Pretrained_on_MSCeleb.pth.tar') File "/home/hyj/anaconda3/envs/hyj_env/lib/python3.8/site-packages/torch/serialization.py", line 608, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "/home/hyj/anaconda3/envs/hyj_env/lib/python3.8/site-packages/torch/serialization.py", line 787, in _legacy_load result = unpickler.load() AttributeError: Can't get attribute 'RecorderMeter' on <module '**main**' from '/home/hyj/桌面/master_projects/MA-Net-main/just_test.py'>

Thanks for your interest.
You can try by adding "import main import RecorderMeter" in your just_test.py.

**Comment by omtrix** [comment]
thanks,it works
