### ISSUE TITLE
pre-training model is damaged

### ISSUE THREAD

**Issue by wwqy** [zengqunzhao/MA-Net#8]
Hello, the contents of the compressed package of pre-training model that I downloaded through Google_drive is damaged. Do you have any other way to download it? Looking for your reply, thank you.

**Comment by zengqunzhao** [comment]
> Hello, the contents of the compressed package of pre-training model that I downloaded through Google_drive is damaged. Do you have any other way to download it? Looking for your reply, thank you.

Hi, please check your code, it should be used as follows:
```
    checkpoint = torch.load('./checkpoint/Pretrained_on_MSCeleb.pth.tar')
    pre_trained_dict = checkpoint['state_dict']
```
